# Generated by Django 3.1.5 on 2021-01-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaumWebtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NaverWebnovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NaverWebtoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
    ]
