# Generated by Django 3.1.5 on 2021-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCrawlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daumwebtoon',
            name='genre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='naverwebnovel',
            name='genre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='naverwebtoon',
            name='genre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='netflix',
            name='genre',
            field=models.CharField(max_length=30),
        ),
    ]
