# Generated by Django 3.1.5 on 2021-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCrawlApp', '0002_auto_20210126_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daumwebtoon',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='naverwebnovel',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='naverwebtoon',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='netflix',
            name='url',
            field=models.URLField(),
        ),
    ]
