# Generated by Django 3.1.5 on 2021-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webCrawlApp', '0003_auto_20210126_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
    ]
