# Generated by Django 3.1.5 on 2021-01-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('lecturer', models.CharField(max_length=30)),
                ('class_room', models.CharField(max_length=30)),
                ('student_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AiStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
