# Generated by Django 3.1.5 on 2021-01-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistudent',
            name='class_num',
        ),
        migrations.AddField(
            model_name='aistudent',
            name='participate_class',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='first_app.aiclass'),
        ),
        migrations.AlterField(
            model_name='aiclass',
            name='student_num',
            field=models.IntegerField(null=True),
        ),
    ]
