# Generated by Django 3.1.5 on 2021-01-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20210121_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudent',
            name='class_num',
            field=models.IntegerField(null=True),
        ),
    ]
