# Generated by Django 3.1.5 on 2021-01-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_aistudent_class_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aistudent',
            name='class_num',
        ),
    ]
