# Generated by Django 3.1.5 on 2021-01-23 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_aistudent_class_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aistudent',
            name='participate_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='first_app.aiclass'),
        ),
    ]
