# Generated by Django 3.1.5 on 2021-01-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20210123_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='aistudent',
            name='interest',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aistudent',
            name='intro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
